###
GET http://localhost:3000/post

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Test",
    "owner": "Idan",
    "content": "Hi Noa!"
}

###

GET http://localhost:3000/post/673e4afe5673b59f80585f4e