###
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "Test",
    "sender": "Noa",
    "content": "Hi Noa!!"
}

###
GET http://localhost:3000/post?sender=Noa



###
GET http://localhost:3000/post/673e50c585d6ea9622c6e75f



###

PUT http://localhost:3000/post/673e50c585d6ea9622c6e75f
Content-Type: application/json

{
    "content": "This is an updated content second time!"
}

###

POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "postId": "673e50c585d6ea9622c6e75f",
    "content": "This is a comment 2",
    "sender": "Noa"
}

###
GET http://localhost:3000/comment/674cdf1ac717f4a1e31808e2