###
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "Test",
    "sender": "Idan",
    "content": "Hi Noa!!"
}

###

GET http://localhost:3000/post/673e4b2d5673b59f80585f51

###
GET http://localhost:3000/post?sender=Noa