###
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "final title pls",
    "sender": "noa",
    "content": "Hi yani!!"
}

###
GET http://localhost:3000/post?sender=idan



###
GET http://localhost:3000/post/67717e1f824304d431169603

###
DELETE http://localhost:3000/post/67718cdad4247984da4720c5



###

PUT http://localhost:3000/post/67717e1f824304d431169603
Content-Type: application/json

{
    "content": "This is an updated content second time!"
}

###

POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "postId": "67718cdad4247984da4720c5",
    "content": "kljzdsfljs is a comment 2",
    "sender": "idan"
}

###
GET http://localhost:3000/comment/67717ef2f3e757717e8616fa

###
PUT http://localhost:3000/comment/67717ef2f3e757717e8616fa
Content-Type: application/json

{
    "postId": "673e50c585d6ea9622c6e75f",
    "content": "This is an updated comment!",
    "sender": "noa44"
}

###
DELETE http://localhost:3000/comment/67717ef2f3e757717e8616fa

###
GET http://localhost:3000/comments/67717e1f824304d431169603



###get user
GET http://localhost:3000/user

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "idanefraim13@gmail.com",
    "username": "idan",
    "password": "secret123"
}

###
GET http://localhost:3000/user/6771817404a76ea1fe6300a6


###

PUT http://localhost:3000/user/6771819504a76ea1fe6300aa
Content-Type: application/json

{
    "email": "noaravski44@gmail.com",
    "username": "noa44",
    "password":"secret123"
}

###
DELETE http://localhost:3000/user/6771819504a76ea1fe6300aa
