###
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "different title",
    "sender": "Noa",
    "content": "Hi Noa!!"
}

###
GET http://localhost:3000/post?sender=Noa



###
GET http://localhost:3000/post/677121dd317e30b221f7c5aa



###

PUT http://localhost:3000/post/677121dd317e30b221f7c5aa
Content-Type: application/json

{
    "content": "This is an updated content second time!"
}

###

POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "postId": "677121dd317e30b221f7c5aa",
    "content": "kljzdsfljs is a comment 2",
    "sender": "Noa"
}

###
GET http://localhost:3000/comment/677121fd317e30b221f7c5b0

###
PUT http://localhost:3000/comment/677121fd317e30b221f7c5b0
Content-Type: application/json

{
    "postId": "673e50c585d6ea9622c6e75f",
    "content": "This is an updated comment!",
    "sender": "Noa"
}

###
DELETE http://localhost:3000/comment/677121fd317e30b221f7c5b0

###
GET http://localhost:3000/comments/677121fd317e30b221f7c5b0