###
GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "final title pls",
    "sender": "idan",
    "content": "Hi yani!!"
}

###
GET http://localhost:3000/post?sender=Noa



###
GET http://localhost:3000/post/67716b078a63f10575af43af



###

PUT http://localhost:3000/post/67716b078a63f10575af43af
Content-Type: application/json

{
    "content": "This is an updated content second time!"
}

###

POST http://localhost:3000/add-comment
Content-Type: application/json

{
    "postId": "67716b078a63f10575af43af",
    "content": "kljzdsfljs is a comment 2",
    "sender": "Noa"
}

###
GET http://localhost:3000/comment/67716dc5c7ea299e3714deaa

###
PUT http://localhost:3000/comment/67716ccc763101a958748dfa
Content-Type: application/json

{
    "postId": "673e50c585d6ea9622c6e75f",
    "content": "This is an updated comment!",
    "sender": "Noa"
}

###
DELETE http://localhost:3000/comment/67716ccc763101a958748dfa

###
GET http://localhost:3000/comments/67716b078a63f10575af43af